- name: 将原有的hosts文件备份
  shell: mv /etc/hosts /etc/hosts_bak

- name: 将ansible端的hosts复制到各自机器上
  copy: src=hosts dest=/etc/ owner=root group=root mode=0644

- name: 在新的hosts文件后面追加各自机器内网ip和hostname
  lineinfile: dest=/etc/hosts line="{{IP}}  {{ansible_hostname}}"

- name: Create a directory if it does not exist
  file:
    path: "{{ install_path }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"    
  tags: install 

- name: copy and extract tarball  #解压压缩包，unarchive模块
  unarchive:
    src:  "{{ tarball_name }}"
    dest: "{{ install_path }}"
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"    
  tags: install

- name: make link  #创建软连接
  shell: ln -s /opt/application/zookeeper-3.4.10 /opt/application/zookeeper;chown "{{ user }}":"{{ user }}" /opt/application/zookeeper* -R 
  tags: install 

- name: Create a zookeeper data directory if it does not exist
  file:
    path: "{{ dataDir }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"    
  tags: install 


- name: update configure   
  template:
    src: "{{ zookeeper_config }}"
    dest: /opt/application/zookeeper/conf/zoo.cfg
    mode: '0755'
    owner: "{{ user }}"    
    group: "{{ user }}"    
  tags: install,updateconfig
  
- name: set myid
  shell: echo "{{id}}" > /opt/application/zookeeper/data/myid
  tags: install,updateconfig

- name: stop zookeeper  
  shell: sh {{install_path}}/{{app_name}}/bin/zkServer.sh stop
  tags: stop
  register: result

- name: start zookeeper  
  shell: sh {{install_path}}/{{app_name}}/bin/zkServer.sh start
  tags: start 
  register: result



- name: yum nc
  shell: which nc || sudo yum install nc -y
  tags: status
  register: result

- name: zookeeper status
  shell: echo mntr | nc 127.0.0.1 2181 | grep follower
  tags: status
  register: result

- name: register stdout
  debug: var=result.stdout_lines
  tags: install,stop,start,status,updateconfig
