apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    selector:
      name: app-nginx
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30003


