apiVersion: v1
kind: Pod
metadata:
    name: app-nginx
    namespace: app
    labels:
      name: app-nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
    - name: nginx-log
      mountPath: /var/log/nginx/
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-data
    hostPath:
        path: /k8s/nginx/html
  - name: nginx-conf
    hostPath:
        path: /k8s/nginx/conf
  - name: nginx-log
    hostPath:
        path: /k8s/nginx/logs
            
  restartPolicy: Never

