apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    selector:
        matchLabels:
            name: nginx
    replicas: 3
    template:
        metadata:
            labels:
                name: nginx
        spec: 
            containers:
            - name: nginx
              image: nginx:latest
              ports: 
              - containerPort: 80
              volumeMounts:
              - name: nginx-data
                mountPath: /usr/share/nginx/html
              - name: nginx-conf
                mountPath: /etc/nginx/conf.d
              - name: nginx-logs
                mountPath: /var/log/nginx
            volumes:
            - name: nginx-data
              nfs:
                path: /data/share/nginx/html
                server: 192.168.8.244
            - name: nginx-conf
              nfs:
                path: /data/share/nginx/conf
                server: 192.168.8.244
            - name: nginx-logs
              nfs:
                path: /data/share/nginx/logs
                server: 192.168.8.244


---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    selector:
      name: nginx
    type: NodePort
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
---


