- name: copy rpm package
  copy:
    src: "{{ tarball_name }}"
    dest: /usr/local/src
  tags: install
- name: install service   #新增service
  shell: sudo yum install -y /usr/local/src/{{ tarball_name }}
  tags: install
- name: add service   #新增service
  template:
    src: "{{ filebeat_config }}"
    dest: /etc/filebeat/filebeat.yml
  tags: install,updateconfig
- name: enable filebeat  #测试nginx配置
  shell: systemctl enable filebeat
  tags: install
- name: check config #测试nginx配置
  shell: filebeat test  config
  notify:
  - start filebeat
  tags: install,start


- name: check config #测试nginx配置
  shell: filebeat test  config
  notify:
  - restart filebeat
  tags: updateconfig
- name: stop filebeat  #测试nginx配置
  shell: systemctl stop filebeat
  tags: stop
- name: status filebeat  #测试nginx配置
  shell: systemctl status filebeat
  tags: status


