- name: install common command
  shell: sudo yum -y install yum-utils vim bind-utils ntpdate sysstat wget man mtr lsof iotop net-tools openssl-devel openssl-perl screen iostat subversion nscd lrzsz  unzip  telnet glances
  tags: install
- name: install common command
  shell: sudo yum -y install gcc gcc-c++ make cmake autoconf bzip2 bzip2-devel curl openssl  rsync gd zip perl httpd-tools    psmisc  epel*  python-pip python-devel      
  tags: install

- name: copy limit.conf
  copy:
    src: limit.conf
    dest: /etc/security/limit.conf
  tags: install
- name: copy sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
  tags: install  
- name: update sysctl
  shell: sudo sysctl -p
  tags: install




