- name: install common command
  shell: sudo yum -y install yum-utils vim bind-utils ntpdate sysstat wget man mtr lsof iotop net-tools openssl-devel openssl-perl screen iostat subversion nscd lrzsz  unzip  telnet glances
  tags: install
- name: copy limits.conf
  copy:
    src: limits.conf
    dest: /etc/security/limits.conf
  become: yes
  become_user: root
  tags: install
- name: copy sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
  become: yes
  become_user: root
  tags: install  
- name: update sysctl
  shell: sysctl -p
  become: yes
  become_user: root
  tags: install
