- name: copy and extract tarball  #解压压缩包，unarchive模块
  unarchive:
    src: "{{ tarball_name }}"
    dest: /usr/local
  tags: install  
- name: make link  #创建软连接
  file: 
    src: /usr/local/jdk1.8.0_251
    dest: /usr/local/jdk
    state: link
  tags: install  
- name: add jdk.sh   #新增jdk.sh
  copy:
    src: "{{ add_path_sh }}"
    dest: /etc/profile.d/
    force: yes
    group: root
    owner: root
    mode: 755  
  tags: install    
- name: update path  
  shell: source /etc/profile.d/jdk.sh
  tags: install
- name: eheck jdk version
  shell: java -version
  tags: install
 

